name: hgsc_subtypes 
channels:
- bioconda
- conda-forge
dependencies:
# - conda-forge::r-base=3.6.3
- conda-forge::r-cluster=2.0.6
- conda-forge::r-curl=3.0
- conda-forge::r-devtools=1.13.3
- conda-forge::r-ggplot2=2.2.1
- conda-forge::r-gplots=3.0.1
- conda-forge::r-gridextra=2.2.1
- conda-forge::r-mnormt=1.5_5
- conda-forge::r-nmf=0.20.6
- conda-forge::r-plyr=1.8.4
- conda-forge::r-proto=0.3_10
- conda-forge::r-scales=0.4.1
- conda-forge::r-stringr=1.1.0
- conda-forge::r-survival=2.41_3
- conda-forge::r-reshape2=1.4.2
- conda-forge::r-reshape=0.8.7
- conda-forge::r-ggally=1.3.2
- conda-forge::r-optparse=1.4.4
- conda-forge::r-venndiagram=1.6.18
- conda-forge::r-outliers=0.14
- conda-forge::r-wgcna=1.51
- conda-forge::pandas=0.22.0
- conda-forge::numpy=1.14.2
- conda-forge::seaborn=0.8.1
- conda-forge::jupyter=1.0.0
- conda-forge::ipykernel=4.8.1
- conda-forge::nb_conda_kernels=2.1.0
- conda-forge::openpyxl=2.5.1
- conda-forge::r-dplyr=0.7.4
- conda-forge::r-tidyr=0.8.0
- conda-forge::r-readr=1.1.1
- conda-forge::r-irkernel=0.8.11
- bioconda::bioconductor-curatedovariandata=1.16.0
- bioconda::bioconductor-affy=1.50.0
- bioconda::bioconductor-annotationdbi=1.38.0
- bioconda::bioconductor-biobase=2.34.0
- bioconda::bioconductor-biocparallel=1.10.1
- bioconda::bioconductor-biomart=2.32.1
- bioconda::bioconductor-doppelgangr=1.4.1
- bioconda::bioconductor-geoquery=2.38.4
- bioconda::bioconductor-go.db=3.4.0
- bioconda::bioconductor-gsva=1.24.1
- bioconda::bioconductor-impute=1.46.0
- bioconda::bioconductor-limma=3.28.2
- bioconda::bioconductor-preprocesscore=1.34.0
- bioconda::bioconductor-siggenes=1.46.0
- bioconda::bioconductor-sva=3.20.0